/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 gang.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/gang.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Кости_ветки" position={[3.011, 1.426, 1.04]}>
          <primitive object={nodes.Bone} />
          <skinnedMesh name="Ветка002" geometry={nodes.Ветка002.geometry} material={materials['Дерево.001']} skeleton={nodes.Ветка002.skeleton} />
        </group>
        <group name="rig001" rotation={[Math.PI, 0, Math.PI]}>
          <primitive object={nodes['DEF-spine003']} />
          <primitive object={nodes['DEF-t_featherL']} />
          <primitive object={nodes['DEF-t_featherR']} />
          <primitive object={nodes['DEF-spine']} />
          <primitive object={nodes['DEF-pelvisL']} />
          <primitive object={nodes['DEF-pelvisR']} />
          <primitive object={nodes['DEF-t_index001L']} />
          <primitive object={nodes['DEF-t_middle001L']} />
          <primitive object={nodes['DEF-t_ring001L']} />
          <primitive object={nodes['DEF-t_thumb001L']} />
          <primitive object={nodes['DEF-t_index001R']} />
          <primitive object={nodes['DEF-t_middle001R']} />
          <primitive object={nodes['DEF-t_ring001R']} />
          <primitive object={nodes['DEF-t_thumb001R']} />
          <primitive object={nodes['DEF-thighL']} />
          <primitive object={nodes['DEF-thighR']} />
          <primitive object={nodes['DEF-w_feather001L']} />
          <primitive object={nodes['DEF-w_feather002L']} />
          <primitive object={nodes['DEF-w_feather003L']} />
          <primitive object={nodes['DEF-w_feather004L']} />
          <primitive object={nodes['DEF-WingL']} />
          <primitive object={nodes['DEF-shoulderL']} />
          <primitive object={nodes['DEF-w_feather001R']} />
          <primitive object={nodes['DEF-w_feather002R']} />
          <primitive object={nodes['DEF-w_feather003R']} />
          <primitive object={nodes['DEF-w_feather004R']} />
          <primitive object={nodes['DEF-WingR']} />
          <primitive object={nodes['DEF-shoulderR']} />
          <primitive object={nodes['DEF-beak001T']} />
          <primitive object={nodes['DEF-beak_001B']} />
          <skinnedMesh name="Snegir_Mesh001" geometry={nodes.Snegir_Mesh001.geometry} material={materials.Snegir} skeleton={nodes.Snegir_Mesh001.skeleton} />
        </group>
        <mesh name="Маленькая_ветка" geometry={nodes.Маленькая_ветка.geometry} material={materials.Дерево} position={[3.163, 4.119, 2.397]} />
      </group>
    </group>
  )
}

useGLTF.preload('/gang.gltf')
